### ISSUE TITLE
Influenza recommended Oct-Mar each year if not done yet that season.

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#105]

**Comment by uladkasach** [comment]
Pull request created, [#135](https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/135). Solution changes the recommended date to Oct 1st for influenza if the recommended date originally falls outside of Oct-Mar

![image](https://cloud.githubusercontent.com/assets/10381896/23763864/597212f2-04c9-11e7-98b9-18dab6868087.png)

**Comment by uladkasach** [comment]
Pull request created, [#136](https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/136). Solution changes the recommended date to Oct 1st for influenza if the recommended date originally falls outside of Oct-Mar

![image](https://cloud.githubusercontent.com/assets/10381896/23763864/597212f2-04c9-11e7-98b9-18dab6868087.png)

The above '3 commits' referencing this issue were due to some git issues. There is only one commit.
