### ISSUE TITLE
Future follow up care and preventive care events should have full box (not just underline) in calendar

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#113]

**Comment by uladkasach** [comment]
Pull request created, https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/140.

- Events now have full boxes (not just underlines) in the calendars
- Event box color is  based on the colors defined for each event ('blended' if there is more than one event in that day).
- Today's date is now only a dashed-outline box, rather than a full color box, reducing its emphasis

![image](https://cloud.githubusercontent.com/assets/10381896/23964223/28442cc2-098a-11e7-9647-13aedc7a3c46.png)
