### ISSUE TITLE
integrate healthy behaviour map into the portal UI/Screens

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#68]
Skip created the fitness centers tool that needs to be integrated within the portal

**Comment by uladkasach** [comment]
Where can we find the code that we will need to host for this?

**Comment by uladkasach** [comment]
Release note: global property `patientportaltoolkit.communities_map_APIKEY` must be defined per https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by uladkasach** [comment]
The code has been significantly rewritten in order to eliminate make it work with our frontend, eliminate bugs, and make it readable. There is one `handler` object which takes care of everything relating to the map and lists. 

As mentioned in the details of the commit, there are two small required improvements left which I will complete before making the final pull request.

**Comment by uladkasach** [comment]
The pull request contains the completed deliverable. Example is shown below:
![screenshot_2017-03-23_13-35-14](https://cloud.githubusercontent.com/assets/10381896/24261502/924b4648-0fcd-11e7-8d0c-653946b690ef.png)
